name: Java CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: "Test on JDK ${{ matrix.java_version }} with ${{ matrix.compiler }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        java_version: [ 17, 21 ]

    steps:
    - name: Checkout for build on JDK ${{ matrix.java_version }}
      uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        check-latest: true
    - name: Build with Maven
      run: |
        ./mvnw --no-transfer-progress --show-version help:effective-settings
        ./mvnw --debug clean verify

